name = "queues-demo"
main = "src/index.js"
compatibility_date = "2026-06-17"

[[kv_namespaces]]
binding = "QUEUE_STATE"
id = "queues-demo"

[[queues.producers]]
binding = "JOBS"
queue = "queues-demo-jobs"

[[queues.consumers]]
queue = "queues-demo-jobs"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
retry_delay = 10
